compile : 
	./compile.sh

clean :
	rm ../build/SideDroid-Desktop.jar
	rm ../bin/SideDroid/Desktop/*.class

archive :
	./archive.sh
run:
	java -jar ../build/SideDroid-Desktop.jar

all: compile archive run
